### ISSUE TITLE
RMI

### ISSUE THREAD

**Issue by 0Rick0** [MightyDuelsDevs/MightyDuels#1]
### RMI

_Het project moet omgebouwd worden zodat het gesplitst is in een client en een server, en dat het communiceert via RMI_
### Mogelijke oplossing

_Implementeren RMI_
### Bestanden

_alle_
### assigment
- @MightyDuelsDevs/mightduelsdevs 
### info
- Door: Rick
- Datum: 16-11-2015

**Comment by Charles-Foster-Kane** [comment]
geimplementeerd moet nog getest worden
