### ISSUE TITLE
Minions

### ISSUE THREAD

**Issue by 0Rick0** [MightyDuelsDevs/MightyDuels#3]
### Minions

_Er moet ondersteuning voor minions toe gevoegd worden_
### Mogelijke oplossing

_De GUI moet minions kunnen weergeven en behandelen en de backend moet Minions kunnen verwerken._
### Bestanden
- GUI Controller
- Match.java
### assigment
- @0RIck0
- @MatthijsZelluf 
### info
- Door: Rick
- Datum: 16-11-2015

**Comment by Charles-Foster-Kane** [comment]
Server kent ze GUI moet nog gefixed worden
