### ISSUE TITLE
Geluid

### ISSUE THREAD

**Issue by 0Rick0** [MightyDuelsDevs/MightyDuels#4]
### Geluid

_Het spel moet achtergrond en voorgrond geluid krijgen_
### Mogelijke oplossing

_Geluid moet gemaakt worden en worden teogevoegd._
### Bestanden

GUI bestanden
### assigment
- @MartijnVanBuul 
### info
- Door: Rick
- Datum: 16-11-2015

**Comment by MartijnVanBuul** [comment]
Controller toegevoegd om het geluid te regelen. Deze heeft een methode Play(String : fileLocation) om een geluid af te spelen. Let op, niet elk geluid kan afgespeeld worden. Probeer ".wav"-files te gebruiken.
