### ISSUE TITLE
Visualisatie damage verwerking

### ISSUE THREAD

**Issue by 0Rick0** [MightyDuelsDevs/MightyDuels#5]
### Visualisatie Damage

_Er moet een visualisatie komen voor het verwerken van de damage_
### Mogelijke oplossing

_-_
### Bestanden
- Match Controller/GUI
### assigment
- @StanWulms 
### info
- Door: Rick
- Datum: 16-11-2015

**Comment by Charles-Foster-Kane** [comment]
implementatie is er maar de kaart van de opponent word niet overgedragen
