### ISSUE TITLE
Rating Implementeren

### ISSUE THREAD

**Issue by 0Rick0** [MightyDuelsDevs/MightyDuels#6]
### Rating

_Er moet een rating worden toegevoegd aan de game_
_Tevens moeten de wins/loses worden geupdate op het profiel en in de database_
### Mogelijke oplossing

_Een algoritme bedenken/zoeken voor de rating te berekenen en dat toe passen_
### Bestanden
- Match.java?
- Database
### assigment
- @TenshiIT 
- @MartijnVanBuul 
### info
- Door: Rick
- Datum: 16-11-2015
- Bewerkt: 5-1-2015 - Ramòn

**Comment by Charles-Foster-Kane** [comment]
geimplementeerd nog niet getest
